GET localhost:3000/url-parameters/all-parameters?sample01="euyrvfjer"&sample02=12344&sampleo3=true

###
GET localhost:3000/url-parameters/mode-parameter-value?mode=123456

###
GET localhost:3000/url-parameters/mode-parameter-value?nomode=true

###