POST localhost:3000/post-payload
Accept: application/json
Content-Type: application/json

{
  "sample_01": "dkjfhgkejrg",
  "sample_02": 236427,
  "sample_03": true
}

###

POST localhost:3000/post-payload
Accept: application/json
Content-Type: application/json

{
  "sample_01": "dkjfhgkejrg",
  "sample_02": 236427,
  "sample_03": "jfdsgvjyefr"
}